In [2]:
import torch


In [3]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [4]:
t2 = torch.tensor([1,2,3,4])
t2

tensor([1, 2, 3, 4])

In [5]:
t3 = torch.tensor([[5.,6],[7,8],[9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
t4 = torch.tensor([[[11,12,13],[13,14,15]],[[15,16,17],[17,18,19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [7]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [9]:
print(t2)
t2.shape

tensor([1, 2, 3, 4])


torch.Size([4])

In [10]:
print(3)
t3.shape

3


torch.Size([3, 2])

In [11]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

The above [2,2,3] means 2 tensors, with 2 rows each and each having 3 elements

In [12]:
#create tensors
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [13]:
#arithmetic operation on tensors
y = w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [14]:
#Computer derivative
y.backward()

In [15]:
#Display gradients
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


# Interoperability with Numpy
Numpy useed for mathematical and scientific computations and is widely used with the following libraries
    - Matplotlib (Plotting and visualizatoin)
    - OpenCV (image and video processing)
    - Pandas (I/O)

PyTorch works well with these and allows operations on tensors.


In [ ]:
import numpy as np

x = np.array()